# Generated by Django 4.1.3 on 2022-11-06 13:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "period_start",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("period_end", models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                "db_table": "historical_context",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEvent",
            fields=[
                ("ogc_fid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "belligerent_1",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "belligerent_2",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "commander_1",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "commander_2",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("strength_1", models.CharField(blank=True, max_length=254, null=True)),
                ("strength_2", models.CharField(blank=True, max_length=254, null=True)),
                ("result", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=3857
                    ),
                ),
                (
                    "historical_context",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hismapapp.historicalcontext",
                    ),
                ),
            ],
            options={
                "db_table": "historical_event",
                "ordering": ["date"],
            },
        ),
    ]
