# Generated by Django 4.1.3 on 2022-11-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hismapapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalcontext",
            name="description",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
