# Generated by Django 4.1.3 on 2022-11-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hismapapp", "0002_historicalcontext_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalevent",
            name="date",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
